name: develop

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
    
      - name: Setup JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Execute Gradle
        uses: eskatos/gradle-command-action@v1
        env:
          github: true
        with:
          arguments: -Pgithub=true clean build    
 
      - name: Docker Publish
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: jeikobu/kotomi-snapshot
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerPassword }}
          registry: https://docker.jeikobu.net
          dockerfile: Dockerfile
        
