name: develop

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
    
      - name: Setup JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Execute Gradle
        uses: eskatos/gradle-command-action@v1
        env:
          github: true
        with:
          arguments: -Pgithub=true clean build    
